// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Psychological.Repository.Models;

public partial class Survey
{
    [Key]
    public int Id { get; set; }

    public int? CategoryId { get; set; }

    public string Description { get; set; }

    public int? Number { get; set; }

    public double? PointAverage { get; set; }

    public int? Verygood { get; set; }

    public int? Good { get; set; }

    public int? Medium { get; set; }

    public int? Bad { get; set; }

    public int? VeryBad { get; set; }

    public int? CreateBy { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual ServeyCategory Category { get; set; }
}