// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Psychological.Repository.Models;

public partial class ServeyCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual ICollection<Survey> Surveys { get; set; } = new List<Survey>();
}