// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PE_PRN231_SP25_00259_QE170035_Repository.Models;

public partial class Brand
{
    [Key]
    public int BrandId { get; set; }

    public string BrandName { get; set; }

    public string Country { get; set; }

    public int? FoundedYear { get; set; }

    public string Website { get; set; }

    public virtual ICollection<Handbag> Handbags { get; set; } = new List<Handbag>();
}