// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PE_PRN231_SP25_00259_QE170035_Repository.Models;

public partial class Handbag
{
    [Key]
    [Required]
    public int HandbagId { get; set; }
    public int? BrandId { get; set; }
    [Required]
    [RegularExpression(@"^([A-Z][a-zA-Z0-9@#]*\s?)+$", ErrorMessage = "Each word in CosmeticName must start with a capital letter.")]
    public string ModelName { get; set; }
    [Required]
    public string Material { get; set; }
    [Required]
    public string Color { get; set; }
    [Required]
    [Range(0.01, double.MaxValue, ErrorMessage = "DollarPrice must be greater than 0.")]
    public decimal? Price { get; set; }
    [Required]
    [Range(1, int.MaxValue, ErrorMessage = "DollarPrice must be at least 1.")]
    public int? Stock { get; set; }
    [Required]
    public DateTime? ReleaseDate { get; set; }

    public virtual Brand Brand { get; set; }
}