// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PE_PRN231_SP25_00259_QE170035_Repository.Models;

public partial class SystemAccount
{
    [Key]
    public int AccountId { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int? Role { get; set; }

    public bool? IsActive { get; set; }
}