// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Psychological.BlazorApp.Client.Models;


public partial class ServeyCategory
{
    [Key]
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime? CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual ICollection<Survey> Surveys { get; set; } = new List<Survey>();
}